server:
  port: 9000
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SemPrace
    username: postgres
    password: 00azz55
    hikari:
      schema: NNPIA
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false