server:
  port: 9000
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 00azz55
  jpa:
    hibernate:
      ddl-auto: create-drop
  liquibase:
    enabled: false